/* Automatisiertes Anlegen der DB-Tabellen Demo Datenmodells
zur Schulung "SQL Script für BW Consultants"
per DDL CREATE Anweisungen */
-- Harald Schütt, 23.04.2020

CREATE COLUMN TABLE banks
(
	bic       VARCHAR(11), --example COBADEFF
	name      NVARCHAR(20),
	street    NVARCHAR(20),
	zipcode   INT,
    place     NVARCHAR(20),
	primary key (bic)
)
COMMENT 'Table with banks';

CREATE COLUMN TABLE bp
(
	id        INT,
	firstname NVARCHAR(20) NOT NULL,
	lastname  NVARCHAR(20) NOT NULL,
	street    NVARCHAR(20),
    zipcode   INT NOT NULL,
    place     NVARCHAR(20),
	primary key (id)
)
COMMENT 'Table with Business Partners (Customers)';

CREATE COLUMN TABLE accounts
(
    id        INT,
	created   DATE NOT NULL,
    type_id   INT NOT NULL,
    type      VARCHAR(8),
    iban      VARCHAR(22) NOT NULL,
	desctxt   NVARCHAR(40),
	primary key (id)
)
COMMENT 'Table with active accounts';

CREATE COLUMN TABLE bk_bp_accnt
(
	id        INT,
	bic       INT,
	bp_id     INT,
	accnt_id  INT,
	desctxt   NVARCHAR(40),
	primary key (id),
	foreign key (bic)
	references banks (bic),
	foreign key (bp_id)
	references bp (id),
	foreign key (accnt_id)
	references accounts (id)
)
COMMENT 'Table with active accounts per bank and per customer';

CREATE COLUMN TABLE error_log
(
    id        INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    timestamp TIMESTAMP,
    errorcode INT,
    message   NVARCHAR(500)
)
COMMENT 'Optional Table for use with functions or procedures';
