/* Kommentare an generierte Views eines aDSOs anhängen
   Kommentare können an den Views selbst oder einzelne
   Felder des Views angehängt werden
   
   SQL-Beispiele
   Kommentar auf Ebene: View
   COMMENT ON VIEW DBVIEW_COM IS 'This is a view comment';
   Kommentar auf Ebene: Feld
   COMMENT ON COLUMN DBVIEW_COM.FIELD_A IS 'This is a view column comment';
*/
SELECT * FROM VIEWS WHERE LIKE '/BIC/A%7';
SELECT * FROM VIEW_COLUMNS WHERE view_name LIKE '/BIC/AADSO_HSC17' ORDER BY POSITION;

COMMENT ON COLUMN "SAPABAP1"."/BIC/AADSO_HSC17"."REQTSN" IS 'Kommentar';

SELECT * FROM SAPABAP1.RSDIOBJ AS IO WHERE OBJVERS = 'A' AND IOBJNM = 'RCAAVKORG';
SELECT * FROM SAPABAP1.RSDIOBJT AS IOT WHERE OBJVERS = 'A' AND LANGU = 'D'AND IOBJNM = 'RCAAVKORG';

SELECT IO.IOBJNM, IO.FIELDNM, IOT.TXTSH, IOT.TXTLG
    FROM SAPABAP1.RSDIOBJ AS IO
    JOIN SAPABAP1.RSDIOBJT AS IOT
      ON IO.IOBJNM = IOT.IOBJNM
     AND IO.OBJVERS = IOT.OBJVERS
     AND IO.OBJVERS = 'A'
     AND IOT.LANGU = 'D'
    WHERE IO.IOBJNM = 'RCAAVKORG';
    
SELECT VW.SCHEMA_NAME, VW.VIEW_NAME, VW.POSITION, VW.COLUMN_NAME, VW.COMMENTS, IO.FIELDNM, IO.IOBJNM, IOT.TXTSH, IOT.TXTLG
    FROM VIEW_COLUMNS AS VW
    LEFT JOIN SAPABAP1.RSDIOBJ AS IO
      ON VW.COLUMN_NAME = IO.FIELDNM
    JOIN SAPABAP1.RSDIOBJT AS IOT
      ON IO.IOBJNM = IOT.IOBJNM
     AND IO.OBJVERS = IOT.OBJVERS
     AND IO.OBJVERS = 'A'
     AND (IOT.LANGU = 'D'OR IOT.LANGU = 'E') 
   WHERE VW.VIEW_NAME = '/BIC/AADSO_HSC17'
   ORDER BY VW.POSITION;