/* Automatisiertes Anlegen der DB-Tabellen Demo Datenmodells
zur Schulung "SQL Script für BW Consultants"
per DDL CREATE Anweisungen */
-- Harald Schütt, 23.04.2020

CREATE COLUMN TABLE banks
(
	name      NVARCHAR(20),
    bic       VARCHAR(11), --example COBADEFF
	street    NVARCHAR(20),
	zipcode   INT,
    place     NVARCHAR(20)
	PRIMARY KEY (
	  name,
	  bic 
	  )
);
CREATE COLUMN TABLE bp
(
	id        INT PRIMARY KEY,
	firstname NVARCHAR(20),
	lastname  NVARCHAR(20),
	street    NVARCHAR(20),
    zipcode   INT,
    place     NVARCHAR(20)
);
CREATE COLUMN TABLE accounts
(
    id        INT PRIMARY KEY,
	created   DATE,
    type_id   INT(2),
    type      VARCHAR(8),
    iban      VARCHAR(22),
	desctxt   NVARCHAR(40)
);
CREATE COLUMN TABLE bk_bp_accnt
(
	id        INT PRIMARY KEY,
	bic       INT FOREIGN KEY bank.bic,
	bp_id     INT FOREIGN KEY bp.id,
	accnt_id  INT FOREIGN KEY accounts.id
	desctxt   NVARCHAR(40)
);
CREATE COLUMN TABLE error_log
(
    id        INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    timestamp TIMESTAMP,
    errorcode INT,
    message   NVARCHAR(500)
);