/* Automatisiertes anlegen des Demo Datenmodells
zur Schulung "SQL Script für BW Consultants"
per DDL CREATE Anweisungen */
-- Harald Schütt, 23.04.2020

CREATE COLUMN TABLE banks
(
	name NVARCHAR(20),
    bic  NVARCHAR(11) --example COBADEFF
);
CREATE COLUMN TABLE bp
(
	id        INT PRIMARY KEY,
	firstname NVARCHAR(20),
	lastname  NVARCHAR(20),
	street    NVARCHAR(20),
    zipcode   INT,
    place     NVARCHAR(20)
);
CREATE COLUMN TABLE accounts
(
    id      INT PRIMARY KEY,
    type_id INT(2),
    type    NVARCHAR(4),
    iban    NVARCHAR(22)
);
CREATE COLUMN TABLE projects
(
	id INT PRIMARY KEY,
	title NVARCHAR
(40),
	project_manager INT,
	estimated_effort INT,
	start_date DATE,
	status int
);
CREATE COLUMN TABLE tasks
(
	id INT PRIMARY KEY,
	project INT,
	title NVARCHAR
(40),
	description CLOB, 
	status INT,
	assignee INT,
	planned_effort INT,
	effort INT,
	create_date DATE,
	due_date DATE,
	completed INT
);
CREATE COLUMN TABLE tasks_log
(
	task INT,
	timestamp TIMESTAMP,
	status INT,
	users INT,
	PRIMARY KEY
(
		task,
		timestamp
	)
);
CREATE COLUMN TABLE error_log
(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    timestamp TIMESTAMP,
    errorcode INT,
    message   NVARCHAR(500)
);